version: '2'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn run dev
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.8-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: dasheddb, dasheddb_test
      POSTGRES_USER: dashed
      POSTGRES_PASSWORD: mypass
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - ./postgres-data:/var/lib/postgresql/data
