version: '2'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn run dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dashed:mypass@postgres/dasheddb
  postgres:
    image: postgres:9.6.8-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dashed
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: dasheddb
    volumes:
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./postgres-data:/var/lib/postgresql/data
